### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by SSapphire666** [MCMrARM/mc-w10-version-launcher#161] opened 2021-12-04 14:12 UTC
![Screenshot 2021-12-04 091928](https://user-images.githubusercontent.com/95534780/144712921-721cfea5-3f9b-4649-a4ef-1ad9210c8fdc.png)
dont know how to do this

**Comment by njt1982** [comment] 2021-12-11 15:19
When that happens it should also open an explorer to the path of the tmp backup. You could rename / zip up / remove that folder as needed.

**Comment by dktapps** [comment] 2021-12-12 17:53
Duplicate of #103

**Closed by dktapps** 2021-12-12 17:53 UTC
