### ISSUE TITLE
Add support for downloading 32 bit versions of Minecraft Bedrock

### ISSUE THREAD

**Issue by ambiennt** [MCMrARM/mc-w10-version-launcher#139] opened 2021-08-14 01:10 UTC
title (also can be marked a suggestion/enhancement). Some people, despite using 64 bit OSs, want to run the 32 bit version of the game because it doesn't include the notorious "render dragon" engine. It seems like 32 bit builds are hard to come across online.

**Comment by ambiennt** [comment] 2021-08-14 01:13
I now see that #134 requests the same thing, but the description was a bit unclear.

**Comment by dktapps** [comment] 2021-09-09 20:44
Duplicate of #114.

**Closed by dktapps** 2021-09-09 20:44 UTC
