### ISSUE TITLE
No Versions

### ISSUE THREAD

**Issue by Terracrafter007** [MCMrARM/mc-w10-version-launcher#70] opened 2021-01-10 22:41 UTC
No verisons
![IMG_20210110_234052](https://user-images.githubusercontent.com/77250459/104137480-566eb980-539d-11eb-953c-1ce41fd708c4.jpg)

**Comment by TwintailFD** [comment] 2021-01-15 13:54
Please check if the 'versions.json' file is missing. If it is missing, please open https://raw.githubusercontent.com/MCMrARM/mc-w10-versiondb/master/versions.json.min and copy all the contents to the versions.json file

**Comment by MCMrARM** [comment] 2021-01-16 12:20
duplicate of #69

**Closed by MCMrARM** 2021-01-16 12:20 UTC
