### ISSUE TITLE
No versions

### ISSUE THREAD

**Issue by netizenw** [MCMrARM/mc-w10-version-launcher#71] opened 2021-01-11 11:59 UTC
when opening the exe, its just a blank screen. anyone help pls

**Comment by Tourniquet88** [comment] 2021-01-11 12:08
Yep I've got the same thing.

According to the Log there's a SSL/TLS issue:

```
List download failed:
System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung. ---> System.Net.WebException: Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine Vertrauensstellung hergestellt werden.. ---> System.Security.Authentication.AuthenticationException: Das Remotezertifikat ist laut Validierungsverfahren ungültig.
   bei System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   bei System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MCLauncher.VersionList.<DownloadList>d__6.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MCLauncher.MainWindow.<<-ctor>b__7_1>d.MoveNext()
```

**Comment by TwintailFD** [comment] 2021-01-15 13:54
> when opening the exe, its just a blank screen. anyone help pls
Please check if the 'versions.json' file is missing. If it is missing, please open https://raw.githubusercontent.com/MCMrARM/mc-w10-versiondb/master/versions.json.min and copy all the contents to the versions.json file

**Comment by Tourniquet88** [comment] 2021-01-16 00:00
Thank you, that was exactly the case. The file was missing.

**Comment by MCMrARM** [comment] 2021-01-16 12:20
duplicate of #69

**Closed by MCMrARM** 2021-01-16 12:20 UTC
