### ISSUE TITLE
Can't download 0.13 version

### ISSUE THREAD

**Issue by Hillionliat** [MCMrARM/mc-w10-version-launcher#88] opened 2021-03-18 09:13 UTC
I am downloading all versions for archiving succeeded in downloading every version except first three 0.13 is this because the files were deleted on Microsoft server if so does anyone have a backup

**Comment by ShyElephant** [comment] 2021-03-24 20:43
no sorry

**Comment by ShyElephant** [comment] 2021-03-24 20:45
hey can u help me i dont know where the exe is can u send me a copy

**Comment by dktapps** [comment] 2021-03-24 21:29
Duplicate of #58

**Closed by dktapps** 2021-03-24 21:29 UTC
