### ISSUE TITLE
Add x86 builds support.

### ISSUE THREAD

**Issue by ItzLightyHD** [MCMrARM/mc-w10-version-launcher#159] opened 2021-11-29 13:22 UTC
### Why?
Since Mojang hasn't fixed yet the RenderDragon engine bugs from 1 year ago (and even 2 years ago if we count both the Xbox One and the PS4 versions) and servers are removing 1.16.x versions support some people are installing the x86 builds of Minecraft Bedrock Edition to escape from input delay and stupid RenderDragon glitches.

### How could it be implemented?
You could add a dropdown to show what build to install for each version.

**Comment by dktapps** [comment] 2021-11-29 17:59
Duplicate of #114.

**Closed by dktapps** 2021-11-29 17:59 UTC
