### ISSUE TITLE
App re-register failed

### ISSUE THREAD

**Issue by dadencukillia** [MCMrARM/mc-w10-version-launcher#174] opened 2022-02-10 09:03 UTC
Pls, help.
Images:
[message](https://ibb.co/94XV05L)
[program](https://ibb.co/1QB5H8q)
Log:
`Download start
GetDownloadUrl() response for updateIdentity ad386d9f-fde0-4a00-b1aa-627f90d5eaa4, revision 1:
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <s:Header>
    <a:Action s:mustUnderstand="1">http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetExtendedUpdateInfo2Response</a:Action>
    <a:RelatesTo>urn:uuid:5754a03d-d8d5-489f-b24d-efc31b3fd32d</a:RelatesTo>
    <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <u:Timestamp u:Id="_0">
        <u:Created>2022-02-10T07:36:42.033Z</u:Created>
        <u:Expires>2022-02-10T07:41:42.033Z</u:Expires>
      </u:Timestamp>
    </o:Security>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <GetExtendedUpdateInfo2Response xmlns="http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService">
      <GetExtendedUpdateInfo2Result>
        <FileLocations>
          <FileLocation>
            <FileDigest>sjy7AHBdPeYr9nF8Jvu80ZSwkSQ=</FileDigest>
            <Url>http://dl.delivery.mp.microsoft.com/filestreamingservice/files/b96965c4-6352-403b-b4f8-5084b075ce3c</Url>
          </FileLocation>
          <FileLocation>
            <FileDigest>Mpu5A02OinplRLY0kiTudlLBAOc=</FileDigest>
            <Url>http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/c453b442-207c-4319-b652-a18c72f2e342?P1=1644490522&amp;P2=404&amp;P3=2&amp;P4=CwZbAhjvpA3XHMqbkkP7QGwmBKqCTmLW%2ff41dpJ9nhgUtXq1g3Lxqr3cw73KyHIIMv5NnDQaT3xossMz5Harng%3d%3d</Url>
          </FileLocation>
        </FileLocations>
      </GetExtendedUpdateInfo2Result>
    </GetExtendedUpdateInfo2Response>
  </s:Body>
</s:Envelope>
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/c453b442-207c-4319-b652-a18c72f2e342?P1=1644490522&P2=404&P3=2&P4=CwZbAhjvpA3XHMqbkkP7QGwmBKqCTmLW%2ff41dpJ9nhgUtXq1g3Lxqr3cw73KyHIIMv5NnDQaT3xossMz5Harng%3d%3d
Actual download started
Download complete
Deleting APPX to reduce disk usage
Registering package
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 51%
Deployment failed: error 0xC0020036: windows.licensing failed to start ClipSvc. Try again and contact the package publisher if the problem persists.
App re-register failed:
System.Exception: Deployment failed: error 0xC0020036: windows.licensing failed to start ClipSvc. Try again and contact the package publisher if the problem persists.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<DeploymentProgressWrapper>d__25.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 222
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<ReRegisterPackage>d__33.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 316
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass24_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 182
Registering package
Deployment progress: Processing 0%
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 51%
Deployment failed: error 0xC0020036: windows.licensing failed to start ClipSvc. Try again and contact the package publisher if the problem persists.
App re-register failed:
System.Exception: Deployment failed: error 0xC0020036: windows.licensing failed to start ClipSvc. Try again and contact the package publisher if the problem persists.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<DeploymentProgressWrapper>d__25.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 222
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<ReRegisterPackage>d__33.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 316
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass24_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 182
`
Thank you for participating. Sorry, I speak English so badly. But I understand well.

**Comment by jarlissao6k** [comment] 2022-02-11 11:36
i'm also getting the error "app re-register failed", but in my case the error says the "dependency "microsoft.services.store.engagement" is missing, please install it..." or something like that. i tried to find and install this dependency but i did not succeed, everything i found about this dependecy was related to visual studio, nuget and other complex developing/coding stuff.
i'm including the log file in the attachment.
sorry for my bad english.

[Log.txt](https://github.com/MCMrARM/mc-w10-version-launcher/files/8048256/Log.txt)

**Comment by dadencukillia** [comment] 2022-02-11 19:56
> 

I too tried to install microsoft.serveces.store.engagement. But I too failed the install. Of course, I used the nuget.
I also tried to use sfc and dism. Result is null. (

**Comment by dktapps** [comment] 2022-06-21 19:51
Duplicate of #135

**Closed by dktapps** 2022-06-21 19:51 UTC
