### ISSUE TITLE
Adding support for downloading 86bit Minecraft bedrock edition for version launcher

### ISSUE THREAD

**Issue by TimothyGrass** [MCMrARM/mc-w10-version-launcher#141] opened 2021-08-17 02:57 UTC
Starting from 1.16.200, Minecraft Bedrock Edition have switched its rendering engine into Render Dragon on its 64 bit version. Meanwhile, their 64 bit version do not support shader anymore but not for the 86 bit version. This issue is asking for the support for launching version from 1.16.200 of the 86 bit version which enables shaders since it is very useful for no matter average players or technical players.

**Comment by D33274D7C6** [comment] 2021-08-17 13:12
> 
> 
> Starting from 1.16.200, Minecraft Bedrock Edition have switched its rendering engine into Render Dragon on its 64 bit version. Meanwhile, their 64 bit version do not support shader anymore but not for the 86 bit version. This issue is asking for the support for launching version from 1.16.200 of the 86 bit version which enables shaders since it is very useful for no matter average players or technical players.

Now, I can ues the "import" to use x86MC

**Comment by ambiennt** [comment] 2021-08-21 10:35
![image](https://user-images.githubusercontent.com/63216972/130319113-34f1a755-3ad2-4a95-a983-534538e34e2c.png)

**Comment by dktapps** [comment] 2021-09-09 20:44
Duplicate of #114.

**Closed by dktapps** 2021-09-09 20:44 UTC
